dist: xenial
notifications:
  slack: ventureum-team:DSE8wxmLTenq0Yz17BrYBWg9
language: node_js
node_js:
  - 8
fail_fast: true
env:
  global:
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY=$AWS_SECRET
    - AWS_DEFAULT_REGION=us-east-1
before_install:
  # set up awscli packages
  - pip install --user awscli
script:
  - npm run eslint
  - npm run flow
  - npm run build
deploy:
  # deploy to AWS
  provider: script
  script: 'npm run upload && make all ENV=staging && make all ENV=test && make all ENV=prod '
  skip_cleanup: true
  on:
    branch: master
true:
  branch: master
